In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Reshape

In [7]:
df = pd.read_csv(
    "data/sudoku.csv",
    nrows=100000,
    dtype=str
)
df.head()

,puzzle,solution
0,0700000430400096108006349000940520003584600200...,6795182435437296188216349577943521863584617292...
1,3010865040465210705000000014008000020803479000...,3719865248465213795924738614638197522853479167...
2,0483015603600080909106700030200009355090102006...,7483915623652487919126754834217869355894132766...
3,0083170000042051090000400703271609049014500000...,2983176457642851391539462783271689549814537266...
4,0408906300001368208007405190004670524500207002...,1428956379751368248367425193984671524513287962...


In [9]:
def string_to_array(s):
    return np.array([int(x) for x in s])

In [8]:
print(type(df["puzzle"][0]))
print(df["puzzle"][0])
print(len(df["puzzle"][0]))

<class 'str'>
070000043040009610800634900094052000358460020000800530080070091902100005007040802
81


In [6]:
print(len(str(df["puzzle"][0])))

80


In [10]:
X = np.array(
    df["puzzle"].apply(string_to_array).tolist()
)

Y = np.array(
    df["solution"].apply(string_to_array).tolist()
)

In [11]:
print(X.shape)
print(Y.shape)

(100000, 81)
(100000, 81)


In [12]:
X = X / 9.0

In [13]:
Y = Y - 1

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [15]:
model = Sequential([

    Dense(
        512,
        activation="relu",
        input_shape=(81,)
    ),

    Dense(
        1024,
        activation="relu"
    ),

    Dense(
        1024,
        activation="relu"
    ),

    Dense(
        81 * 9,
        activation="softmax"
    ),

    Reshape((81, 9))

])

c:\Users\alex_\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [17]:
history = model.fit(
    X_train,
    Y_train,
    validation_split=0.1,
    epochs=20,
    batch_size=128
)

Epoch 1/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1571 - loss: 2.1295 - val_accuracy: 0.1697 - val_loss: 2.0907
Epoch 2/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 30s 53ms/step - accuracy: 0.1875 - loss: 2.0420 - val_accuracy: 0.2045 - val_loss: 1.9769
Epoch 3/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 28s 50ms/step - accuracy: 0.2239 - loss: 1.9329 - val_accuracy: 0.2275 - val_loss: 1.9194
Epoch 4/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 34s 61ms/step - accuracy: 0.2499 - loss: 1.8869 - val_accuracy: 0.2469 - val_loss: 1.8845
Epoch 5/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 32s 56ms/step - accuracy: 0.2791 - loss: 1.8316 - val_accuracy: 0.2718 - val_loss: 1.8356
Epoch 6/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 30s 54ms/step - accuracy: 0.3082 - loss: 1.7701 - val_accuracy: 0.2899 - val_loss: 1.7919
Epoch 7/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 37s 65ms/step - accuracy: 0.3339 - loss: 1.7137 - val_accuracy: 0.3104 - val_loss: 1.7507
Epoch 8/20
563/563 ━━━━━━━━━━━━━━━━━━━━ 34s 61ms/step - accuracy: 0.3564 - loss: 1.6646 - 

In [18]:
loss, acc = model.evaluate(
    X_test,
    Y_test
)

print("Accuracy:", acc)

625/625 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.4304 - loss: 1.4846
Accuracy: 0.4303518533706665


In [25]:
model.save("sudoku_solver.keras")

In [20]:
matriz = np.array([

[7,0,0,0,0,0,4,3,0],
[4,0,0,0,9,6,1,0,8],
[0,0,0,0,0,0,0,0,0],

[8,3,1,7,0,0,0,0,4],
[2,0,5,1,0,9,0,0,0],
[0,4,0,1,4,5,0,0,0],

[0,0,0,0,0,0,0,4,5],
[0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0]

])

In [26]:
from tensorflow.keras.models import load_model

solver = load_model(
    "sudoku_solver.keras"
)

In [27]:
entrada = matriz.flatten()

In [28]:
entrada = matriz.flatten()

In [31]:
import numpy as np

entrada = np.array(entrada)

entrada = entrada.reshape(1, 81)

print(entrada.shape)

pred = solver.predict(entrada)

(1, 81)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 328ms/step


In [29]:
print(solver.input_shape)

(None, 81)


In [30]:
print(type(entrada))
print(entrada.shape)
print(entrada)

<class 'numpy.ndarray'>
(81,)
[7 0 0 0 0 0 4 3 0 4 0 0 0 9 6 1 0 8 0 0 0 0 0 0 0 0 0 8 3 1 7 0 0 0 0 4 2
 0 5 1 0 9 0 0 0 0 4 0 1 4 5 0 0 0 0 0 0 0 0 0 0 4 5 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [32]:
pred = solver.predict(entrada)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


In [33]:
solucion = np.argmax(
    pred,
    axis=2
) + 1

In [34]:
solucion = solucion.reshape(9,9)

In [35]:
print(solucion)

[[9 1 1 1 1 7 1 1 1]
 [1 8 8 1 1 8 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [8 1 1 1 8 7 1 1 1]
 [8 1 1 1 8 1 1 1 1]
 [1 1 1 1 1 8 1 1 1]
 [1 1 1 1 1 1 1 1 8]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]
