In [1]:
import numpy as np
import pandas as pd
import cv2
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.models import load_model

In [2]:
df = pd.read_csv("data/sudoku.csv", nrows=100000)
df.shape

(100000, 2)

In [3]:
df.head()

,puzzle,solution
0,7000004304000961080063490009405200035846002000...,6795182435437296188216349577943521863584617292...
1,3010865040465210705000000014008000020803479000...,3719865248465213795924738614638197522853479167...
2,4830156036000809091067000302000093550901020067...,7483915623652487919126754834217869355894132766...
3,8317000004205109000040070327160904901450000045...,2983176457642851391539462783271689549814537266...
4,4089063000013682080074051900046705245002070026...,1428956379751368248367425193984671524513287962...


In [7]:
import numpy as np

# Cargar la matriz que guardó el Modelo 2
sudoku_a_resolver = np.load("../modelo_class/sudoku_detectado.npy") 
# (Asegúrate de poner la ruta correcta de carpetas según tu estructura de Git)

print("Matriz cargada en el Modelo 3 lista para resolver:")
print(sudoku_a_resolver)

Matriz cargada en el Modelo 3 lista para resolver:
[[0 0 2 7 0 6 4 9 3]
 [5 0 0 0 0 0 6 0 0]
 [0 0 7 0 2 0 5 8 0]
 [0 0 5 6 3 0 8 0 0]
 [0 0 3 0 0 5 0 0 2]
 [4 7 8 0 0 9 0 0 0]
 [0 5 0 0 0 0 2 0 6]
 [3 0 0 0 4 0 0 0 0]
 [0 0 0 3 6 0 7 0 0]]


In [9]:
# =========================================================================
# 3. CONEXIÓN Y PREDICCIÓN PERFECTA DE TU SUDOKU REAL (DEL MODELO 2)
# =========================================================================
print("\n" + "=" * 40)
print("PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)")
print("=" * 40)

# 1. Cargamos la matriz limpia de 9x9 que guardaste con el Modelo 2
try:
    mi_sudoku_yolo = np.load("../modelo_class/sudoku_detectado.npy")
    print("Matriz detectada del Modelo 2 cargada con éxito:")
    print(mi_sudoku_yolo)
except FileNotFoundError:
    print(
        "No se encontró 'sudoku_detectado.npy'. Asegúrate de la ruta de carpetas."
    )
    # Tablero de prueba por si acaso
    mi_sudoku_yolo = np.array(
        [
            [5, 3, 0, 0, 7, 0, 0, 0, 0],
            [6, 0, 0, 1, 9, 5, 0, 0, 0],
            [0, 9, 8, 0, 0, 0, 0, 6, 0],
            [8, 0, 0, 0, 6, 0, 0, 0, 3],
            [4, 0, 0, 8, 0, 3, 0, 0, 1],
            [7, 0, 0, 0, 2, 0, 0, 0, 6],
            [0, 6, 0, 0, 0, 0, 2, 8, 0],
            [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9],
        ]
    )

# 2. Copiamos el Sudoku original para transformarlo paso a paso de forma limpia
sudoku_prediseno = mi_sudoku_yolo.copy().astype(np.float32)

# Normalizamos exactamente igual que en el set de entrenamiento
sudoku_normalizado = (sudoku_prediseno / 9.0) - 0.5
sudoku_input = sudoku_normalizado.reshape(1, 9, 9, 1)

# 3. Realizar la predicción en el modelo entrenado
predicciones_prob = model_resolver.predict(sudoku_input, verbose=0)  # (1, 81, 9)

# 4. Decodificar asegurando la ausencia total de ceros (mapeo estricto del 1 al 9)
sudoku_final_lista = []
for i, celda_prob in enumerate(predicciones_prob[0]):
    # Tomamos el índice con mayor probabilidad (da un número de 0 a 8)
    indice_maximo = np.argmax(celda_prob)

    # Convertimos de vuelta al valor real sumando 1 (da un número del 1 al 9)
    numero_solucion = int(indice_maximo + 1)
    sudoku_final_lista.append(numero_solucion)

# Reconstruimos la matriz final en formato 9x9
sudoku_resuelto_final = np.array(sudoku_final_lista).reshape(9, 9)

print("\n¡SUDOKU RESUELTO POR LA RED NEURONAL!")
print(sudoku_resuelto_final)

# Guardar la solución final
np.save("sudoku_solucionado.npy", sudoku_resuelto_final)
print("\nMatriz guardada en 'sudoku_solucionado.npy' lista para la entrega.")


PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)
Matriz detectada del Modelo 2 cargada con éxito:
[[0 0 2 7 0 6 4 9 3]
 [5 0 0 0 0 0 6 0 0]
 [0 0 7 0 2 0 5 8 0]
 [0 0 5 6 3 0 8 0 0]
 [0 0 3 0 0 5 0 0 2]
 [4 7 8 0 0 9 0 0 0]
 [0 5 0 0 0 0 2 0 6]
 [3 0 0 0 4 0 0 0 0]
 [0 0 0 3 6 0 7 0 0]]


NameError: name 'model_resolver' is not defined

In [5]:
# =========================================================================
# 3. CONEXIÓN Y PREDICCIÓN PERFECTA DE TU SUDOKU REAL (DEL MODELO 2)
# =========================================================================
print("\n" + "=" * 40)
print("PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)")
print("=" * 40)

# 1. Cargamos la matriz limpia de 9x9 que guardaste con el Modelo 2
try:
    mi_sudoku_yolo = np.load("../modelo_class/sudoku_detectado.npy")
    print("Matriz detectada del Modelo 2 cargada con éxito:")
    print(mi_sudoku_yolo)
except FileNotFoundError:
    print(
        "No se encontró 'sudoku_detectado.npy'. Asegúrate de la ruta de carpetas."
    )
    # Tablero de prueba por si acaso
    mi_sudoku_yolo = np.array(
        [
            [5, 3, 0, 0, 7, 0, 0, 0, 0],
            [6, 0, 0, 1, 9, 5, 0, 0, 0],
            [0, 9, 8, 0, 0, 0, 0, 6, 0],
            [8, 0, 0, 0, 6, 0, 0, 0, 3],
            [4, 0, 0, 8, 0, 3, 0, 0, 1],
            [7, 0, 0, 0, 2, 0, 0, 0, 6],
            [0, 6, 0, 0, 0, 0, 2, 8, 0],
            [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9],
        ]
    )

# 2. Copiamos el Sudoku original para transformarlo paso a paso de forma limpia
sudoku_prediseno = mi_sudoku_yolo.copy().astype(np.float32)

# Normalizamos exactamente igual que en el set de entrenamiento
sudoku_normalizado = (sudoku_prediseno / 9.0) - 0.5
sudoku_input = sudoku_normalizado.reshape(1, 9, 9, 1)

# 3. Realizar la predicción en el modelo entrenado
predicciones_prob = model_resolver.predict(sudoku_input, verbose=0)  # (1, 81, 9)

# 4. Decodificar asegurando la ausencia total de ceros (mapeo estricto del 1 al 9)
sudoku_final_lista = []
for i, celda_prob in enumerate(predicciones_prob[0]):
    # Tomamos el índice con mayor probabilidad (da un número de 0 a 8)
    indice_maximo = np.argmax(celda_prob)

    # Convertimos de vuelta al valor real sumando 1 (da un número del 1 al 9)
    numero_solucion = int(indice_maximo + 1)
    sudoku_final_lista.append(numero_solucion)

# Reconstruimos la matriz final en formato 9x9
sudoku_resuelto_final = np.array(sudoku_final_lista).reshape(9, 9)

print("\n¡SUDOKU RESUELTO POR LA RED NEURONAL!")
print(sudoku_resuelto_final)

# Guardar la solución final
np.save("sudoku_solucionado.npy", sudoku_resuelto_final)
print("\nMatriz guardada en 'sudoku_solucionado.npy' lista para la entrega.")


PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)
Matriz detectada del Modelo 2 cargada con éxito:
[[0 0 2 7 0 6 4 9 3]
 [5 0 0 0 0 0 6 0 0]
 [0 0 7 0 2 0 5 8 0]
 [0 0 5 6 3 0 8 0 0]
 [0 0 3 0 0 5 0 0 2]
 [4 7 8 0 0 9 0 0 0]
 [0 5 0 0 0 0 2 0 6]
 [3 0 0 0 4 0 0 0 0]
 [0 0 0 3 6 0 7 0 0]]


NameError: name 'model_resolver' is not defined

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import (
    Activation,
    BatchNormalization,
    Conv2D,
    Dense,
    Flatten,
    Input,
    Reshape,
    add,
)
from tensorflow.keras.models import Model

# =========================================================================
# 1. CARGA Y PREPROCESAMIENTO DEL DATASET DE CLASE
# =========================================================================
print("Cargando dataset de Sudokus...")
# Leemos 100,000 filas para que tenga suficiente variedad lógica
df = pd.read_csv("data/sudoku.csv", nrows=100000)


def preprocesar_datos(df):
    X = np.array([np.array(list(q)).astype(np.float32) for q in df["quizzes"]])
    y = np.array([np.array(list(s)).astype(np.int32) for s in df["solutions"]])

    # Normalización idónea para Sudokus
    X = (X / 9) - 0.5
    X = X.reshape(-1, 9, 9, 1)

    y = y - 1  # Clases de 0 a 8
    y = y.reshape(-1, 81)
    return X, y


X_train, y_train = preprocesar_datos(df)

# =========================================================================
# 2. ARQUITECTURA AVANZADA DE DEEP LEARNING (Especial Sudokus)
# =========================================================================
# Usamos la API funcional de Keras para poder bifurcar los análisis
input_layer = Input(shape=(9, 9, 1))

# Rama 1: Analizar bloques locales (Cuadrantes de 3x3)
r1 = Conv2D(64, kernel_size=(3, 3), activation="relu", padding="same")(
    input_layer
)
r1 = BatchNormalization()(r1)

# Rama 2: Analizar FILAS completas (Kernel de 1x9)
r2 = Conv2D(64, kernel_size=(1, 9), activation="relu", padding="same")(
    input_layer
)
r2 = BatchNormalization()(r2)

# Rama 3: Analizar COLUMNAS completas (Kernel de 9x1)
r3 = Conv2D(64, kernel_size=(9, 1), activation="relu", padding="same")(
    input_layer
)
r3 = BatchNormalization()(r3)

# Fusionar la información de las tres perspectivas lógicas
fusion = tf.keras.layers.concatenate([r1, r2, r3])

# Capas profundas de extracción de características cruzadas
x = Conv2D(128, kernel_size=(3, 3), activation="relu", padding="same")(fusion)
x = BatchNormalization()(x)
x = Conv2D(128, kernel_size=(3, 3), activation="relu", padding="same")(x)
x = BatchNormalization()(x)

x = Flatten()(x)

# Redes densas lógicas
x = Dense(1024, activation="relu")(x)
x = Dense(81 * 9)(x)
x = Reshape((81, 9))(x)

output_layer = Activation("softmax", name="salida_probabilidades")(x)

# Construir modelo final
model_resolver = Model(inputs=input_layer, outputs=output_layer)

model_resolver.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

print("\nEntrenando la red neuronal optimizada...")
# Subimos ligeramente las épocas a 8 y bajamos el batch_size para ajustar mejor
model_resolver.fit(
    X_train, y_train, batch_size=32, epochs=8, validation_split=0.1
)

model_resolver.save("modelo3_resolver_sudoku.keras")
print("¡Modelo 3 entrenado y guardado!")

# =========================================================================
# 3. CONEXIÓN Y PREDICCIÓN PERFECTA DE TU SUDOKU REAL (DEL MODELO 2)
# =========================================================================
print("\n" + "=" * 40)
print("PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)")
print("=" * 40)

# 1. Cargamos la matriz limpia de 9x9 que guardaste con el Modelo 2
try:
    mi_sudoku_yolo = np.load("../modelo_class/sudoku_detectado.npy")
    print("Matriz detectada del Modelo 2 cargada con éxito:")
    print(mi_sudoku_yolo)
except FileNotFoundError:
    print(
        "No se encontró 'sudoku_detectado.npy'. Asegúrate de la ruta de carpetas."
    )
    # Tablero de prueba por si acaso
    mi_sudoku_yolo = np.array(
        [
            [5, 3, 0, 0, 7, 0, 0, 0, 0],
            [6, 0, 0, 1, 9, 5, 0, 0, 0],
            [0, 9, 8, 0, 0, 0, 0, 6, 0],
            [8, 0, 0, 0, 6, 0, 0, 0, 3],
            [4, 0, 0, 8, 0, 3, 0, 0, 1],
            [7, 0, 0, 0, 2, 0, 0, 0, 6],
            [0, 6, 0, 0, 0, 0, 2, 8, 0],
            [0, 0, 0, 4, 1, 9, 0, 0, 5],
            [0, 0, 0, 0, 8, 0, 0, 7, 9],
        ]
    )

# 2. Copiamos el Sudoku original para transformarlo paso a paso de forma limpia
sudoku_prediseno = mi_sudoku_yolo.copy().astype(np.float32)

# Normalizamos exactamente igual que en el set de entrenamiento
sudoku_normalizado = (sudoku_prediseno / 9.0) - 0.5
sudoku_input = sudoku_normalizado.reshape(1, 9, 9, 1)

# 3. Realizar la predicción en el modelo entrenado
predicciones_prob = model_resolver.predict(sudoku_input, verbose=0)  # (1, 81, 9)

# 4. Decodificar asegurando la ausencia total de ceros (mapeo estricto del 1 al 9)
sudoku_final_lista = []
for i, celda_prob in enumerate(predicciones_prob[0]):
    # Tomamos el índice con mayor probabilidad (da un número de 0 a 8)
    indice_maximo = np.argmax(celda_prob)

    # Convertimos de vuelta al valor real sumando 1 (da un número del 1 al 9)
    numero_solucion = int(indice_maximo + 1)
    sudoku_final_lista.append(numero_solucion)

# Reconstruimos la matriz final en formato 9x9
sudoku_resuelto_final = np.array(sudoku_final_lista).reshape(9, 9)

print("\n¡SUDOKU RESUELTO POR LA RED NEURONAL!")
print(sudoku_resuelto_final)

# Guardar la solución final
np.save("sudoku_solucionado.npy", sudoku_resuelto_final)
print("\nMatriz guardada en 'sudoku_solucionado.npy' lista para la entrega.")

Cargando dataset de Sudokus...


KeyError: 'quizzes'

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import (
    BatchNormalization,
    Conv2D,
    Dense,
    Flatten,
    Input,
    Reshape,
)
from tensorflow.keras.models import Sequential

# =========================================================================
# 1. CARGA Y PREPROCESAMIENTO DEL DATASET DE CLASE
# =========================================================================
print("Cargando dataset de Sudokus...")
# Cambia la ruta por la ubicación real de tu 'sudoku.csv'
df = pd.read_csv("data/sudoku.csv", nrows=100000)

# Tomamos una muestra (por ejemplo 20,000 o 50,000) para que no tarde una eternidad en entrenar
# df = df.sample(20000, random_state=42)


def preprocesar_datos(df):
    X = np.array(
        [np.array(list(q)).astype(np.float32) for q in df["quizzes"]]
    )  # 81 caracteres
    y = np.array(
        [np.array(list(s)).astype(np.int32) for s in df["solutions"]]
    )  # 81 caracteres

    # Normalización típica de Sudoku en redes (restar 0.5 para centrar los datos)
    X = (X / 9) - 0.5
    X = X.reshape(-1, 9, 9, 1)

    # Las soluciones las dejamos como enteros para sparse_categorical_crossentropy
    # Restamos 1 para que las clases vayan de 0 a 8 (el número 1 será clase 0, el 9 clase 8)
    y = y - 1
    y = y.reshape(-1, 81)

    return X, y


X_train, y_train = preprocesar_datos(df)

# =========================================================================
# 2. CREACIÓN DEL MODELO DE DEEP LEARNING PARA RESOLVER
# =========================================================================
# Una arquitectura convolucional profunda es idónea para aprender las relaciones de filas/columnas
model_resolver = Sequential(
    [
        Input(shape=(9, 9, 1)),
        # Primera capa convolucional para captar relaciones locales (cuadrantes)
        Conv2D(64, kernel_size=(3, 3), activation="relu", padding="same"),
        BatchNormalization(),
        Conv2D(64, kernel_size=(3, 3), activation="relu", padding="same"),
        BatchNormalization(),
        # Segunda capa para conectar filas y columnas completas
        Conv2D(128, kernel_size=(3, 3), activation="relu", padding="same"),
        BatchNormalization(),
        Flatten(),
        # Capa densa que procesa la lógica global del tablero
        Dense(512, activation="relu"),
        # Salida: necesitamos predecir 9 posibles números para cada una de las 81 celdas
        Dense(81 * 9),
        Reshape((81, 9), name="salida_probabilidades"),
        tf.keras.layers.Activation("softmax"),
    ]
)

model_resolver.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

print("\nEntrenando la red para resolver Sudokus...")
model_resolver.fit(X_train, y_train, batch_size=64, epochs=5, validation_split=0.1)

# Guardamos el modelo para no perder el entrenamiento
model_resolver.save("modelo3_resolver_sudoku.keras")
print("¡Modelo 3 entrenado y guardado!")

# =========================================================================
# 3. CONEXIÓN CON TU MATRIZ DEL MODELO 2
# =========================================================================
print("\n" + "=" * 40)
print("PREDICIENDO TU SUDOKU REAL (DEL MODELO 2)")
print("=" * 40)

# 1. Cargamos la matriz limpia de 9x9 que guardaste con el Modelo 2
try:
    mi_sudoku_yolo = np.load("../modelo_class/sudoku_detectado.npy")
    print("Matriz detectada del Modelo 2 cargada:")
    print(mi_sudoku_yolo)
except FileNotFoundError:
    print(
        "No se encontró 'sudoku_detectado.npy'. Usando una matriz de prueba genérica por si acaso."
    )
    mi_sudoku_yolo = np.zeros((9, 9), dtype=np.int32)  # Fallback ficticio

# 2. Preprocesar la matriz exactamente igual que el conjunto de entrenamiento
mi_sudoku_input = mi_sudoku_yolo.flatten().astype(np.float32)
mi_sudoku_input = (mi_sudoku_input / 9) - 0.5
mi_sudoku_input = mi_sudoku_input.reshape(1, 9, 9, 1)

# 3. Hacer la predicción del Sudoku completo
prediccion = model_resolver.predict(mi_sudoku_input, verbose=0)  # Shape (1, 81, 9)

# 4. Decodificar la predicción (obtener el número con mayor probabilidad en cada celda)
sudoku_final_lista = []
for celda in prediccion[0]:
    numero_predicho = (
        np.argmax(celda) + 1
    )  # Sumamos 1 porque restamos 1 en el preprocesamiento
    sudoku_final_lista.append(numero_predicho)

# Convertir de nuevo a formato visual de matriz 9x9
sudoku_resuelto_final = np.array(sudoku_final_lista).reshape(9, 9)

print("\n¡SUDOKU RESUELTO POR LA RED NEURONAL!")
print(sudoku_resuelto_final)

Cargando dataset de Sudokus...


KeyError: 'quizzes'

In [ ]:
import numpy as np

# 1. CARGAR LA MATRIZ DETECTADA POR EL MODELO 2
# Ajusta la ruta si tus carpetas se llaman de otra forma
try:
    sudoku = np.load("sudoku_detectado.npy")
    print("Matriz original cargada con éxito:")
    print(sudoku)
    print("-" * 30)
except FileNotFoundError:
    print("No se encontró el archivo 'sudoku_detectado.npy'. Asegúrate de haber ejecutado el Modelo 2.")


# 2. FUNCIONES DE VALIDACIÓN LÓGICA (Reglas del Sudoku)
def es_valido(matriz, num, fila, col):
    """Comprueba si un número se puede colocar en una posición determinada."""
    # Verificar la fila
    if num in matriz[fila, :]:
        return False

    # Verificar la columna
    if num in matriz[:, col]:
        return False

    # Verificar el cuadrante 3x3
    ini_fila = (fila // 3) * 3
    ini_col = (col // 3) * 3
    sub_matriz = matriz[ini_fila : ini_fila + 3, ini_col : ini_col + 3]

    if num in sub_matriz:
        return False

    return True


def encontrar_vacia(matriz):
    """Busca la siguiente casilla con un 0."""
    for i in range(9):
        for j in range(9):
            if matriz[i, j] == 0:
                return i, j  # Devuelve la coordenada (fila, columna)
    return None


# 3. ALGORITMO RECURSIVO DE BACKTRACKING
def resolver_sudoku(matriz):
    """Resuelve el tablero modificando la matriz por referencia."""
    casilla = encontrar_vacia(matriz)

    # Si no hay casillas vacías, ¡el Sudoku está resuelto!
    if not casilla:
        return True

    fila, col = casilla

    # Probar números del 1 al 9
    for num in range(1, 10):
        if es_valido(matriz, num, fila, col):
            matriz[fila, col] = num  # Asignación tentativa

            # Llamada recursiva para el siguiente número
            if resolver_sudoku(matriz):
                return True

            # Si no funcionó, deshacemos el cambio (Backtrack)
            matriz[fila, col] = 0

    return False


# 4. EJECUTAR EL RESOLVEDOR
# Hacemos una copia para no destruir la matriz original importada
sudoku_resuelto = sudoku.copy()

if resolver_sudoku(sudoku_resuelto):
    print("\n¡Sudoku Resuelto Correctamente por el Modelo 3!")
    print(sudoku_resuelto)

    # (Opcional) Puedes exportar la solución final si la necesitas
    np.save("sudoku_solucionado.npy", sudoku_resuelto)
else:
    print(
        "\nNo se pudo resolver. Revisa si el Modelo 2 introdujo algún número erróneo."
    )